services:
  carrental-gateway:
    image: ${DOCKER_REGISTRY-}carrentalgateway
    build:
      context: .
      dockerfile: CarRental.Gateway/Dockerfile
    depends_on:
      - jk-inventory-webapi
      - maintenance-webapi
      - customer-webapi
    networks:
      - appnetwork

  carrental-mvc:
    image: ${DOCKER_REGISTRY-}carrentalmvc
    build:
      context: .
      dockerfile: CarRental.MVC/Dockerfile
    depends_on:
      - carrental-gateway
    networks:
      - appnetwork

  customer-webapi:
    image: ${DOCKER_REGISTRY-}customerwebapi
    build:
      context: .
      dockerfile: Customer.WebAPI/Dockerfile
    networks:
      - appnetwork

  maintenance-webapi:
    image: ${DOCKER_REGISTRY-}maintenancewebapi
    build:
      context: .
      dockerfile: Maintenance.WebAPI/Dockerfile
    networks:
      - appnetwork

  jk-inventory-webapi:
    image: ${DOCKER_REGISTRY-}jkinventorywebapi
    build:
      context: .
      dockerfile: Inventory/JK_Inventory.WebAPI/Dockerfile
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge
