apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: jk-inventory-webapi
  name: jk-inventory-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: jk-inventory-webapi
  template:
    metadata:
      labels:
        io.kompose.service: jk-inventory-webapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_URLS
              value: http://+:8080
          image: jkinventorywebapi
          name: jk-inventory-webapi
          ports:
            - containerPort: 8080
              protocol: TCP
      restartPolicy: Always
