// <auto-generated />
using JK_Inventory.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace JK_Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(JK_InventoryContext))]
    [Migration("20260315035149_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.Inventory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleLocationId")
                        .HasColumnType("int");

                    b.Property<int>("VehicleStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.HasIndex("VehicleLocationId");

                    b.HasIndex("VehicleStatusId");

                    b.ToTable("Inventory", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            VehicleId = 1,
                            VehicleLocationId = 1,
                            VehicleStatusId = 1
                        },
                        new
                        {
                            Id = 2,
                            VehicleId = 2,
                            VehicleLocationId = 1,
                            VehicleStatusId = 2
                        },
                        new
                        {
                            Id = 3,
                            VehicleId = 3,
                            VehicleLocationId = 2,
                            VehicleStatusId = 1
                        },
                        new
                        {
                            Id = 4,
                            VehicleId = 4,
                            VehicleLocationId = 2,
                            VehicleStatusId = 3
                        },
                        new
                        {
                            Id = 5,
                            VehicleId = 5,
                            VehicleLocationId = 3,
                            VehicleStatusId = 1
                        },
                        new
                        {
                            Id = 6,
                            VehicleId = 6,
                            VehicleLocationId = 3,
                            VehicleStatusId = 4
                        },
                        new
                        {
                            Id = 7,
                            VehicleId = 1,
                            VehicleLocationId = 4,
                            VehicleStatusId = 1
                        },
                        new
                        {
                            Id = 8,
                            VehicleId = 2,
                            VehicleLocationId = 4,
                            VehicleStatusId = 2
                        },
                        new
                        {
                            Id = 9,
                            VehicleId = 3,
                            VehicleLocationId = 1,
                            VehicleStatusId = 1
                        },
                        new
                        {
                            Id = 10,
                            VehicleId = 4,
                            VehicleLocationId = 2,
                            VehicleStatusId = 3
                        });
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("Vehicle", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1
                        },
                        new
                        {
                            Id = 2
                        },
                        new
                        {
                            Id = 3
                        },
                        new
                        {
                            Id = 4
                        },
                        new
                        {
                            Id = 5
                        },
                        new
                        {
                            Id = 6
                        });
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleLocation", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Kitchener"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Waterloo"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cambridge"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Guelph"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleStatus", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Available"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Reserved"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Rented"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Maintenance"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("VehicleType", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Sedan"
                        },
                        new
                        {
                            Id = 2,
                            Name = "SUV"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Truck"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Van"
                        });
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.Inventory", b =>
                {
                    b.HasOne("Inventory.Domain.AggregatesModel.InventoryAggregate.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .IsRequired();

                    b.HasOne("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleLocation", "Location")
                        .WithMany()
                        .HasForeignKey("VehicleLocationId")
                        .IsRequired();

                    b.HasOne("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleStatus", "Status")
                        .WithMany()
                        .HasForeignKey("VehicleStatusId")
                        .IsRequired();

                    b.Navigation("Location");

                    b.Navigation("Status");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Inventory.Domain.AggregatesModel.InventoryAggregate.Vehicle", b =>
                {
                    b.OwnsOne("Inventory.Domain.AggregatesModel.InventoryAggregate.VehicleCode", "VehicleCode", b1 =>
                        {
                            b1.Property<int>("VehicleId")
                                .HasColumnType("int");

                            b1.Property<string>("Make")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Make");

                            b1.Property<string>("Model")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)")
                                .HasColumnName("Model");

                            b1.Property<int>("Type")
                                .HasColumnType("int")
                                .HasColumnName("VehicleTypeId");

                            b1.HasKey("VehicleId");

                            b1.ToTable("Vehicle");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");

                            b1.HasData(
                                new
                                {
                                    VehicleId = 1,
                                    Make = "Toyota",
                                    Model = "Camry",
                                    Type = 1
                                },
                                new
                                {
                                    VehicleId = 2,
                                    Make = "Honda",
                                    Model = "Civic",
                                    Type = 1
                                },
                                new
                                {
                                    VehicleId = 3,
                                    Make = "Ford",
                                    Model = "Escape",
                                    Type = 2
                                },
                                new
                                {
                                    VehicleId = 4,
                                    Make = "Toyota",
                                    Model = "RAV4",
                                    Type = 2
                                },
                                new
                                {
                                    VehicleId = 5,
                                    Make = "Ford",
                                    Model = "F-150",
                                    Type = 3
                                },
                                new
                                {
                                    VehicleId = 6,
                                    Make = "Chevy",
                                    Model = "Express",
                                    Type = 4
                                });
                        });

                    b.Navigation("VehicleCode")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
