apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    io.kompose.service: carrental-mvc-claim1
  name: carrental-mvc-claim1
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Mi
