apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\blitz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.dev-db.yml --out k8s-manifests/
    kompose.version: 1.38.0 (a8f5d1cbd)
  labels:
    io.kompose.service: customer-webapi
  name: customer-webapi
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: customer-webapi
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\blitz\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.dev-db.yml --out k8s-manifests/
        kompose.version: 1.38.0 (a8f5d1cbd)
      labels:
        io.kompose.service: customer-webapi
    spec:
      containers:
        - env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Docker
            - name: ASPNETCORE_URLS
              value: http://+:8080
          image: customerwebapi
          imagePullPolicy: Never
          name: customer-webapi
          ports:
            - containerPort: 8080
              protocol: TCP
          volumeMounts:
            - mountPath: /home/app/.microsoft/usersecrets
              name: customer-webapi-claim0
              readOnly: true
            - mountPath: /home/app/.aspnet/https
              name: customer-webapi-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: customer-webapi-claim0
          persistentVolumeClaim:
            claimName: customer-webapi-claim0
            readOnly: true
        - name: customer-webapi-claim1
          persistentVolumeClaim:
            claimName: customer-webapi-claim1
            readOnly: true
